### ISSUE TITLE
issue with Deal and hit button

### ISSUE THREAD

**Issue by Dmo582251** [Dmo582251/blackJack_game-WDI-Project-1#2]
WHAT USER STORY YOU ARE WORKING ON:

I am working on the user story "when user clicks on hit and deal"

WHAT YOU ARE TRYING TO DO:

I am trying to have the card value shown when the dealer deals. / value of third card is added when hit

DETAILED DESCRIPTION OF THE BUG/ERROR:
dealer and player have the same cards right now.. dont know when that happened
hit value is not adding

WHAT I'VE TRIED
I've used debug to print out the object
 i tried switching up my code 
tried making a new function just for hit getting value

I did update in the rails console, but it worked fine, and the changes showed up on the view.

QUESTION

Why do my player and dealer have the same card when they are not the same
how come my hit function for player not working when i even made a new function just so it can be added?

@awongh @pavankat @DBrodsky90 @WilliamfShaw

**Comment by WilliamfShaw** [comment]
@Dmo582251 Can you give me a more detailed view of the code your using?

**Comment by Dmo582251** [comment]
// DEAL BUTTON
var Dealer = function() {
  this.deck = new Deck();
  this.hand = new Hand();
  this.handValue = 0;
  this.stay = true;

  this.deal = function(randomCard){

```
//pushing cards into dealer hand
this.hand.hand.push(randomCard);
this.hand.getValue();
console.log(this.hand.value);

//pushes cards into players hand
player.hand.hand.push(randomCard);
player.hand.getValue();
console.log("cards have been added to dealer and players hands");
```

  };

///DEAL BUTTON
var dealButton = $('#deal')
        dealButton.text("Deal");
        dealButton.click(function(){
            dealer.deal(deck.getRandomCard());
            dealer.deal(deck.getRandomCard());

```
    //Showing player card values
    var playerCardValue = $("#playerCardValue");
        //DOESNT WORK(playerCardValue.player.hand.hand.value);
    var playerCard1 = $("#playerCard1");
        //DOESNT WORKplayerCard1.text(player.hand.hand[0].value);
    var playerCard2 = $("#playerCard2");
        //DOESNT WORKplayerCard1.text(player.hand.hand[0].value);



    //Showing dealer card values
    var dealerCardValue =$("#dealerCardValue");
        (dealerCardValue.dealer.hand.hand.value);
    var dealerCard1 = $("#dealerCard1");
        dealerCard1.text(dealer.hand.hand[0].value);
    var dealerCard2 = $("#dealerCard2")
        dealerCard2.text(dealer.hand.hand[1].value);
    });
```

**Comment by Dmo582251** [comment]
HIT BUTTON:::::
    var hitButton = $('#hit')
        hitButton.text("Hit")
        hitButton.click(function(){
            //only hits once..
            player.hand.hit(deck.getRandomCard());

```
    //Showing player card values
    var playerCard1 = $("#playerCard1");
        console.log(player.hand.hand[0].value);
    var playerCard2 = $("#playerCard2");
        playerCard2.text(player.hand.hand[1].value);


    //Showing dealer card values
    var dealerCard1 = $("#dealerCard1");
        dealerCard1.text(dealer.hand.hand[0].value);
    var dealerCard2 = $("#dealerCard2")
        dealerCard2.text(dealer.hand.hand[1].value);
    });
```

**Comment by Dmo582251** [comment]
```
/*Deal button
-------------------------------------*/
var dealButton = $('#deal')
    dealButton.text("Deal");
    dealButton.click(function(){
        dealer.deal(deck.getRandomCard());
        dealer.deal(deck.getRandomCard());

    //Showing player card values
    var playerCardValue = $("#playerCardValue");
        //DOESNT WORK(playerCardValue.player.hand.hand.value);
    var playerCard1 = $("#playerCard1");
        //DOESNT WORKplayerCard1.text(player.hand.hand[0].value);
    var playerCard2 = $("#playerCard2");
        //DOESNT WORKplayerCard1.text(player.hand.hand[0].value);



    //Showing dealer card values
    var dealerCardValue =$("#dealerCardValue");
        (dealerCardValue.dealer.hand.hand.value);
    var dealerCard1 = $("#dealerCard1");
        dealerCard1.text(dealer.hand.hand[0].value);
    var dealerCard2 = $("#dealerCard2")
        dealerCard2.text(dealer.hand.hand[1].value);
    });
```

**Comment by WilliamfShaw** [comment]
@Dmo582251 kewl!! So let me ask you a question........Does the dealer have access to the player inside of its own constructor????????

Where could you build an object that would hold all of your game logic that would make more sense. That could have access to the dealer and the player and the winning logic?

**Comment by Dmo582251** [comment]
can we chat in person?<3

**Comment by Dmo582251** [comment]
and i mean i guess so considering when i do click the button an array of two cards goes into the players hand
